
package fr.afcepf.atod21.covoiturage.servicesimpl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import fr.afcepf.atod21.covoiturage.services.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "desInscriptionTrajetServiceSoap", targetNamespace = "http://services.coVoiturage.atod21.afcepf.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DesInscriptionTrajetServiceSoap {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "desInscrireTrajetDto", targetNamespace = "http://services.coVoiturage.atod21.afcepf.fr/", className = "fr.afcepf.atod21.covoiturage.services.DesInscrireTrajetDto")
    @ResponseWrapper(localName = "desInscrireTrajetDtoResponse", targetNamespace = "http://services.coVoiturage.atod21.afcepf.fr/", className = "fr.afcepf.atod21.covoiturage.services.DesInscrireTrajetDtoResponse")
    public boolean desInscrireTrajetDto(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
