
package fr.afcepf.atod21.covoiturage.servicesimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DesInscriptionTrajetServiceSoapService", targetNamespace = "http://servicesImpl.coVoiturage.atod21.afcepf.fr/", wsdlLocation = "http://192.168.11.52:8080/CoVoiturage_web/ws/SOAP/DesInscriptionTrajetService?wsdl")
public class DesInscriptionTrajetServiceSoapService
    extends Service
{

    private final static URL DESINSCRIPTIONTRAJETSERVICESOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException DESINSCRIPTIONTRAJETSERVICESOAPSERVICE_EXCEPTION;
    private final static QName DESINSCRIPTIONTRAJETSERVICESOAPSERVICE_QNAME = new QName("http://servicesImpl.coVoiturage.atod21.afcepf.fr/", "DesInscriptionTrajetServiceSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.11.52:8080/CoVoiturage_web/ws/SOAP/DesInscriptionTrajetService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DESINSCRIPTIONTRAJETSERVICESOAPSERVICE_WSDL_LOCATION = url;
        DESINSCRIPTIONTRAJETSERVICESOAPSERVICE_EXCEPTION = e;
    }

    public DesInscriptionTrajetServiceSoapService() {
        super(__getWsdlLocation(), DESINSCRIPTIONTRAJETSERVICESOAPSERVICE_QNAME);
    }

    public DesInscriptionTrajetServiceSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DESINSCRIPTIONTRAJETSERVICESOAPSERVICE_QNAME, features);
    }

    public DesInscriptionTrajetServiceSoapService(URL wsdlLocation) {
        super(wsdlLocation, DESINSCRIPTIONTRAJETSERVICESOAPSERVICE_QNAME);
    }

    public DesInscriptionTrajetServiceSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DESINSCRIPTIONTRAJETSERVICESOAPSERVICE_QNAME, features);
    }

    public DesInscriptionTrajetServiceSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DesInscriptionTrajetServiceSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DesInscriptionTrajetServiceSoap
     */
    @WebEndpoint(name = "DesInscriptionTrajetServiceSoapPort")
    public DesInscriptionTrajetServiceSoap getDesInscriptionTrajetServiceSoapPort() {
        return super.getPort(new QName("http://servicesImpl.coVoiturage.atod21.afcepf.fr/", "DesInscriptionTrajetServiceSoapPort"), DesInscriptionTrajetServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DesInscriptionTrajetServiceSoap
     */
    @WebEndpoint(name = "DesInscriptionTrajetServiceSoapPort")
    public DesInscriptionTrajetServiceSoap getDesInscriptionTrajetServiceSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicesImpl.coVoiturage.atod21.afcepf.fr/", "DesInscriptionTrajetServiceSoapPort"), DesInscriptionTrajetServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DESINSCRIPTIONTRAJETSERVICESOAPSERVICE_EXCEPTION!= null) {
            throw DESINSCRIPTIONTRAJETSERVICESOAPSERVICE_EXCEPTION;
        }
        return DESINSCRIPTIONTRAJETSERVICESOAPSERVICE_WSDL_LOCATION;
    }

}
