
package fr.afcepf.atod21.covoiturage.servicesimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConnexionServiceSoapService", targetNamespace = "http://servicesImpl.coVoiturage.atod21.afcepf.fr/", wsdlLocation = "http://192.168.11.52:8080/CoVoiturage_web/ws/SOAP/ConnexionService?wsdl")
public class ConnexionServiceSoapService
    extends Service
{

    private final static URL CONNEXIONSERVICESOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONNEXIONSERVICESOAPSERVICE_EXCEPTION;
    private final static QName CONNEXIONSERVICESOAPSERVICE_QNAME = new QName("http://servicesImpl.coVoiturage.atod21.afcepf.fr/", "ConnexionServiceSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.11.52:8080/CoVoiturage_web/ws/SOAP/ConnexionService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONNEXIONSERVICESOAPSERVICE_WSDL_LOCATION = url;
        CONNEXIONSERVICESOAPSERVICE_EXCEPTION = e;
    }

    public ConnexionServiceSoapService() {
        super(__getWsdlLocation(), CONNEXIONSERVICESOAPSERVICE_QNAME);
    }

    public ConnexionServiceSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONNEXIONSERVICESOAPSERVICE_QNAME, features);
    }

    public ConnexionServiceSoapService(URL wsdlLocation) {
        super(wsdlLocation, CONNEXIONSERVICESOAPSERVICE_QNAME);
    }

    public ConnexionServiceSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONNEXIONSERVICESOAPSERVICE_QNAME, features);
    }

    public ConnexionServiceSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConnexionServiceSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IConnexionServiceSoap
     */
    @WebEndpoint(name = "ConnexionServiceSoapPort")
    public IConnexionServiceSoap getConnexionServiceSoapPort() {
        return super.getPort(new QName("http://servicesImpl.coVoiturage.atod21.afcepf.fr/", "ConnexionServiceSoapPort"), IConnexionServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IConnexionServiceSoap
     */
    @WebEndpoint(name = "ConnexionServiceSoapPort")
    public IConnexionServiceSoap getConnexionServiceSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicesImpl.coVoiturage.atod21.afcepf.fr/", "ConnexionServiceSoapPort"), IConnexionServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONNEXIONSERVICESOAPSERVICE_EXCEPTION!= null) {
            throw CONNEXIONSERVICESOAPSERVICE_EXCEPTION;
        }
        return CONNEXIONSERVICESOAPSERVICE_WSDL_LOCATION;
    }

}
