
package fr.afcepf.atod21.covoiturage.servicesimpl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import fr.afcepf.atod21.covoiturage.services.ObjectFactory;
import fr.afcepf.atod21.covoiturage.services.UtilisateurDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IConnexionServiceSoap", targetNamespace = "http://services.coVoiturage.atod21.afcepf.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IConnexionServiceSoap {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns fr.afcepf.atod21.covoiturage.services.UtilisateurDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "seConnecterSOAP", targetNamespace = "http://services.coVoiturage.atod21.afcepf.fr/", className = "fr.afcepf.atod21.covoiturage.services.SeConnecterSOAP")
    @ResponseWrapper(localName = "seConnecterSOAPResponse", targetNamespace = "http://services.coVoiturage.atod21.afcepf.fr/", className = "fr.afcepf.atod21.covoiturage.services.SeConnecterSOAPResponse")
    public UtilisateurDto seConnecterSOAP(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
