
package fr.afcepf.atod21.covoiturage.servicesimpl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IOException", targetNamespace = "http://services.coVoiturage.atod21.afcepf.fr/")
public class IOException
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private fr.afcepf.atod21.covoiturage.services.IOException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public IOException(String message, fr.afcepf.atod21.covoiturage.services.IOException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IOException(String message, fr.afcepf.atod21.covoiturage.services.IOException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fr.afcepf.atod21.covoiturage.services.IOException
     */
    public fr.afcepf.atod21.covoiturage.services.IOException getFaultInfo() {
        return faultInfo;
    }

}
