
package fr.afcepf.atod21.covoiturage.servicesimpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import fr.afcepf.atod21.covoiturage.services.ObjectFactory;
import fr.afcepf.atod21.covoiturage.services.TrajetDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IOrchestrateurSoap", targetNamespace = "http://services.coVoiturage.atod21.afcepf.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IOrchestrateurSoap {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws IOException
     * @throws Exception
     * @throws FileNotFoundException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authentifierClient", targetNamespace = "http://services.coVoiturage.atod21.afcepf.fr/", className = "fr.afcepf.atod21.covoiturage.services.AuthentifierClient")
    @ResponseWrapper(localName = "authentifierClientResponse", targetNamespace = "http://services.coVoiturage.atod21.afcepf.fr/", className = "fr.afcepf.atod21.covoiturage.services.AuthentifierClientResponse")
    public int authentifierClient(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws Exception, FileNotFoundException, IOException
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<fr.afcepf.atod21.covoiturage.services.TrajetDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercherTrajetParVilleDepartSOAP", targetNamespace = "http://services.coVoiturage.atod21.afcepf.fr/", className = "fr.afcepf.atod21.covoiturage.services.RechercherTrajetParVilleDepartSOAP")
    @ResponseWrapper(localName = "rechercherTrajetParVilleDepartSOAPResponse", targetNamespace = "http://services.coVoiturage.atod21.afcepf.fr/", className = "fr.afcepf.atod21.covoiturage.services.RechercherTrajetParVilleDepartSOAPResponse")
    public List<TrajetDto> rechercherTrajetParVilleDepartSOAP(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<fr.afcepf.atod21.covoiturage.services.TrajetDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercherTrajetSOAP", targetNamespace = "http://services.coVoiturage.atod21.afcepf.fr/", className = "fr.afcepf.atod21.covoiturage.services.RechercherTrajetSOAP")
    @ResponseWrapper(localName = "rechercherTrajetSOAPResponse", targetNamespace = "http://services.coVoiturage.atod21.afcepf.fr/", className = "fr.afcepf.atod21.covoiturage.services.RechercherTrajetSOAPResponse")
    public List<TrajetDto> rechercherTrajetSOAP(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws IOException
     * @throws Exception
     * @throws FileNotFoundException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "entryMethod", targetNamespace = "http://services.coVoiturage.atod21.afcepf.fr/", className = "fr.afcepf.atod21.covoiturage.services.EntryMethod")
    @ResponseWrapper(localName = "entryMethodResponse", targetNamespace = "http://services.coVoiturage.atod21.afcepf.fr/", className = "fr.afcepf.atod21.covoiturage.services.EntryMethodResponse")
    public boolean entryMethod(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws Exception, FileNotFoundException, IOException
    ;

}
